INSERT INTO TMB01MT (userId)VALUES (UUID_TO_BIN(UUID()));
INSERT INTO TMB01MT (userId)VALUES (UUID_TO_BIN(UUID()));
INSERT INTO TMB01MT (userId)VALUES (UUID_TO_BIN(UUID()));
INSERT INTO TMB01MT (userId)VALUES (UUID_TO_BIN(UUID()));
INSERT INTO TMB01MT (userId)VALUES (UUID_TO_BIN(UUID()));


